#!/usr/bin/env python3
import feedparser
import time
from datetime import datetime

def get_rss_feed(url):
    feed = feedparser.parse(url)
    return feed

rss_url = "https://www.farsnews.ir/rss"

last_entry_time = None
timing_list = []

while True:
    feed_data = get_rss_feed(rss_url)

    if feed_data.bozo == 1:
        print("Error parsing the feed.")
    else:
        for entry in feed_data.entries:
            print("\n---")
            print(f"Title: {entry.title}")
            print(f"Published: {entry.published}")

            # Calculate time passed since the last entry
            current_entry_time = datetime.strptime(entry.published, "%a, %d %b %Y %H:%M:%S %Z")
            if last_entry_time:
                time_passed = last_entry_time - current_entry_time
                if time_passed != "0:00:00":
                    minute = (str(time_passed)).split(":")
                    timing_list.append(int(minute[1]))
                print(f"Time Passed: {time_passed}")
            last_entry_time = current_entry_time
    mean_time = sum(timing_list)/len(timing_list)
    print(f"\naverage time for new rss : {mean_time}")
    print("\nWaiting for the next refresh...")
    time.sleep(mean_time*60)
